### ISSUE TITLE
Hello It's Tomasz_Sacha

### ISSUE THREAD

**Issue by Tsacha100** [ThomasHoussin/com.thomashoussin.fronius#10]
This is the results you asked for.

{
Body: {
Data: {
1: {
Current_AC_Phase_1: 1.238,
Current_AC_Phase_2: 0.716,
Current_AC_Phase_3: 1.767,
Details: {
Manufacturer: "Fronius",
Model: "Smart Meter 63A",
Serial: "19120661"
},
Enable: 1,
EnergyReactive_VArAC_Sum_Consumed: 8078360,
EnergyReactive_VArAC_Sum_Produced: 6987770,
EnergyReal_WAC_Minus_Absolute: 3514081,
EnergyReal_WAC_Plus_Absolute: 3550052,
EnergyReal_WAC_Sum_Consumed: 3550052,
EnergyReal_WAC_Sum_Produced: 3514081,
Frequency_Phase_Average: 50,
Meter_Location_Current: 0,
PowerApparent_S_Phase_1: 294.76779999999997,
PowerApparent_S_Phase_2: 172.7708,
PowerApparent_S_Phase_3: 425.847,
PowerApparent_S_Sum: 828.12,
PowerFactor_Phase_1: 0.99,
PowerFactor_Phase_2: -0.99,
PowerFactor_Phase_3: 1,
PowerFactor_Sum: 1,
PowerReactive_Q_Phase_1: -23.4,
PowerReactive_Q_Phase_2: 16.43,
PowerReactive_Q_Phase_3: -12.99,
PowerReactive_Q_Sum: -19.96,
PowerReal_P_Phase_1: 261.75,
PowerReal_P_Phase_2: 170.01,
PowerReal_P_Phase_3: 396.36,
PowerReal_P_Sum: 828.12,
TimeStamp: 1617732119,
Visible: 1,
Voltage_AC_PhaseToPhase_12: 415.2,
Voltage_AC_PhaseToPhase_23: 417.7,
Voltage_AC_PhaseToPhase_31: 414.9,
Voltage_AC_Phase_1: 238.1,
Voltage_AC_Phase_2: 241.3,
Voltage_AC_Phase_3: 241
}
}
},
Head: {
RequestArguments: {
DeviceClass: "Meter",
Scope: "System"
},
Status: {
Code: 0,
Reason: "",
UserMessage: ""
},
Timestamp: "2021-04-06T20:01:59+02:00"
}
}

**Comment by ThomasHoussin** [comment]
I think I found the bug ; if you could try the latest test version and report what you can see in the smartmeter device. Thanks

**Comment by Tsacha100** [comment]
Thanks I think it's working now. 
![image](https://user-images.githubusercontent.com/82055161/113874610-46a51c80-97b6-11eb-970a-dbe80c219f2f.png)

**Comment by ThomasHoussin** [comment]
Great, thanks for your feedback
