### ISSUE TITLE
Pull don’t work after update. 

### ISSUE THREAD

**Issue by mrJakobsson** [ThomasHoussin/com.thomashoussin.fronius#14]
New version doesn’t pull data from inverter or smart meter every 60s during work hours but will update when I coming home. So if I look at insights then it’s fixed on value shown when leaving the house until I get back home.

**Comment by ThomasHoussin** [comment]
Hi. I doubt this is related to the update : position or smartphone is not used in the app. The update was an upgrade to API v3, I don't think anything network related has changed in the new version. I'll have a look nevertheless.

**Comment by mrJakobsson** [comment]
Strange things are happening with my homey right now. But I got fronius up and running again after firmware update on datamanager. Thanks for a great app.

**Comment by ThomasHoussin** [comment]
Ok thanks, I'll close the issue then.
