### ISSUE TITLE
Fronius WATTPILOT support

### ISSUE THREAD

**Issue by EEEjhacker** [ThomasHoussin/com.thomashoussin.fronius#18]
Hi,
we are working on a digitalization project in the energy sector and started to use the Fronius App for HOMEY. Everything is working fine until now, so really great app. What we actually have not found on the App is the option to integrate the FRONIUS WATTPILOT wallbox.

So the question is, if you have planned to integrate it. If yes, until when the feature will be available?

THX

**Comment by ThomasHoussin** [comment]
Hi, 
There is no API documentation available for the Fronius Wattpilot. If Fronius releases an API, I'll have a look and probably integrate it. 

Regards
Thomas

**Comment by ahochsteger** [comment]
The API is using JSON messages over websockets.
See here for more information:
https://github.com/safepay/sensor.fronius/issues/48#issuecomment-932501077

**Comment by ThomasHoussin** [comment]
No documented API available
