### ISSUE TITLE
SmartMeter  - no Display

### ISSUE THREAD

**Issue by robgreiner** [ThomasHoussin/com.thomashoussin.fronius#2]
Hi,
I User the App with Fronius GEN24 and the display for the smart meter does not show any values.
Kind regards 
Robert

**Comment by ThomasHoussin** [comment]
Hi
GEN24 is not supposed to be different for smart meter, I'll have a look.  

Could you please open in your browser http://<your_ip>/solar_api/v1/GetMeterRealtimeData.cgi?Scope=System and paste the result please ?

Regards

**Comment by robgreiner** [comment]
{
   "Body" : {
      "Data" : {
         "0" : {
            "ACBRIDGE_CURRENT_ACTIVE_MEAN_01_F32" : 0.77600000000000002,
            "ACBRIDGE_CURRENT_ACTIVE_MEAN_02_F32" : 0.67000000000000004,
            "ACBRIDGE_CURRENT_ACTIVE_MEAN_03_F32" : 1.8120000000000001,
            "ACBRIDGE_VOLTAGE_MEAN_12_F32" : 402.30000000000001,
            "ACBRIDGE_VOLTAGE_MEAN_23_F32" : 401.89999999999998,
            "ACBRIDGE_VOLTAGE_MEAN_31_F32" : 401.69999999999999,
            "COMPONENTS_MODE_ENABLE_U16" : 1.0,
            "COMPONENTS_MODE_VISIBLE_U16" : 1.0,
            "COMPONENTS_TIME_STAMP_U64" : 1607875761.0,
            "Details" : {
               "Manufacturer" : "Fronius",
               "Model" : "Smart Meter 63A",
               "Serial" : "20290366"
            },
            "GRID_FREQUENCY_MEAN_F32" : 50.0,
            "SMARTMETER_ENERGYACTIVE_ABSOLUT_MINUS_F64" : 276271.0,
            "SMARTMETER_ENERGYACTIVE_ABSOLUT_PLUS_F64" : 755602.0,
            "SMARTMETER_ENERGYACTIVE_CONSUMED_SUM_F64" : 755602.0,
            "SMARTMETER_ENERGYACTIVE_PRODUCED_SUM_F64" : 276271.0,
            "SMARTMETER_ENERGYREACTIVE_CONSUMED_SUM_F64" : 164340.0,
            "SMARTMETER_ENERGYREACTIVE_PRODUCED_SUM_F64" : 4114390.0,
            "SMARTMETER_FACTOR_POWER_01_F64" : 0.77000000000000002,
            "SMARTMETER_FACTOR_POWER_02_F64" : 0.87,
            "SMARTMETER_FACTOR_POWER_03_F64" : 0.91000000000000003,
            "SMARTMETER_FACTOR_POWER_SUM_F64" : 0.88,
            "SMARTMETER_POWERACTIVE_01_F64" : 101.68000000000001,
            "SMARTMETER_POWERACTIVE_02_F64" : 127.56999999999999,
            "SMARTMETER_POWERACTIVE_03_F64" : 337.04000000000002,
            "SMARTMETER_POWERACTIVE_MEAN_01_F64" : 101.52006688963203,
            "SMARTMETER_POWERACTIVE_MEAN_02_F64" : 40.13230769230767,
            "SMARTMETER_POWERACTIVE_MEAN_03_F64" : 320.26785953177279,
            "SMARTMETER_POWERACTIVE_MEAN_SUM_F64" : 566.28999999999996,
            "SMARTMETER_POWERAPPARENT_01_F64" : 180.1096,
            "SMARTMETER_POWERAPPARENT_02_F64" : 155.70800000000003,
            "SMARTMETER_POWERAPPARENT_03_F64" : 419.84039999999999,
            "SMARTMETER_POWERAPPARENT_MEAN_01_F64" : 178.95992508361215,
            "SMARTMETER_POWERAPPARENT_MEAN_02_F64" : 113.63860468227429,
            "SMARTMETER_POWERAPPARENT_MEAN_03_F64" : 393.69103244147169,
            "SMARTMETER_POWERAPPARENT_MEAN_SUM_F64" : 638.0,
            "SMARTMETER_POWERREACTIVE_01_F64" : -82.569999999999993,
            "SMARTMETER_POWERREACTIVE_02_F64" : -68.640000000000001,
            "SMARTMETER_POWERREACTIVE_03_F64" : -144.74000000000001,
            "SMARTMETER_POWERREACTIVE_MEAN_SUM_F64" : -295.94999999999999,
            "SMARTMETER_VALUE_LOCATION_U16" : 0.0,
            "SMARTMETER_VOLTAGE_01_F64" : 232.09999999999999,
            "SMARTMETER_VOLTAGE_02_F64" : 232.40000000000001,
            "SMARTMETER_VOLTAGE_03_F64" : 231.69999999999999,
            "SMARTMETER_VOLTAGE_MEAN_01_F64" : 231.95518394648826,
            "SMARTMETER_VOLTAGE_MEAN_02_F64" : 232.06421404682254,
            "SMARTMETER_VOLTAGE_MEAN_03_F64" : 231.64113712374609
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Meter",
         "Scope" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2020-12-13T16:09:21+00:00"
   }
}

**Comment by ThomasHoussin** [comment]
Thanks. From what I found, this is some kind of bug in some GEN24 firmware version. I think I can add an option to workaround that, I'll keep you updated.

**Comment by ThomasHoussin** [comment]
Commit #34c4b75 should fix it.  For now I added a new parameter in advanced settings "use workaround for GEN24 smartmeter" ; if you activate it, you should have the correct values (I had to guess and compute some values, so if something seems weird please report it). 

It's in the test version here : https://homey.app/fr-fr/app/com.thomashoussin.fronius/Fronius/test/

**Comment by robgreiner** [comment]
It works!
Thank you very much Thomas
regards
Robert

**Comment by ThomasHoussin** [comment]
Great, I'll add it to the next stable version.

**Comment by ThomasHoussin** [comment]
Now in the stable version
