### ISSUE TITLE
Possibility to read load per phase?

### ISSUE THREAD

**Issue by Fewk1** [ThomasHoussin/com.thomashoussin.fronius#22]
Thank you for a great app, easy to install and running smoothly. I wonder if it would be possible to get more data from the smart meter. Specifically I would be interested in read load per phase in order to balance the load to a charging box. 
The loads are displayed on the smart meter itself, but I cannot get the readings to the other units in the system.

Best
/Fredrik

**Comment by ThomasHoussin** [comment]
Hi. Yes I think I can add that ; would current per phase be enough ?

**Comment by Fewk1** [comment]
Yes, current per phase would be perfect. 

Thank you

/Fredrik

**Comment by ThomasHoussin** [comment]
Hi. Can you try the test version : https://homey.app/a/com.thomashoussin.fronius/test/

I added a setting (in advanced settings) to activate 3-phase visibility, I think it should work.

**Comment by Fewk1** [comment]
Thank you Thomas, 

It seems to work fine, I get readouts that correspond to the numbers on the smart meter display. I see that you have also added flow triggers for each👍🏻
My only suggestion would be to assign different names to the phases, since they now all have the same name, see screen image below. Ström is current in Swedish. I would suggest Ström L1, etc. 




Again thanks for fixing this so rapidly. Kudos!

/Fredrik

**Comment by ThomasHoussin** [comment]
I forgot that, it fixed it in new test version.

**Comment by Fewk1** [comment]
Thanks  again works like a charm!

Best regards 
/Fredrik
