### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by AlecWW** [ThomasHoussin/com.thomashoussin.fronius#25]
Hi,

Thank you so much for developing an app for Fronius devices! I just got my Homey Pro and this was the very first app I installed, however, in the setup process when trying to add my inverter I get "Error: Could not find that PairSession". It is probably a very dumb mistake on my part but I would appreciate some guidance if possible. 

Regards

**Comment by ThomasHoussin** [comment]
Hi. Do you use the stable or the test version of the app ? When does this happen, after entering the IP address ? Thanks

**Comment by DirkReimelt** [comment]
I have the same problem. In which format do I add the IP? xxx.xxx.xxx.xxx does not work.

**Comment by ThomasHoussin** [comment]
Do you use stable or test version ? For me this error only happens when you wait too long before entering IP address (may be one minute or two)

Yes you can enter the IP address xxx.xxx.xxx.xxx it should work

**Comment by DirkReimelt** [comment]
Thanks Thomas for your reply. I love the App and it was working till yesterday. Previously I did manage to connect but don’t remember.
After it stoped showing results yesterday I deinstalled the inverter as device but kept the SmartMeter. I also kept the App itself installed. Then I tried to add the inverter as a device and added the IP right away. It was just some seconds. I wonder what is wrong? Or should I Deinstallation everything (all devices and the App) and install it again? I am really lost and have no idea what to do.
Dirk

**Comment by DirkReimelt** [comment]
I don’t know if stable version or test version. How can I know?

**Comment by ThomasHoussin** [comment]
I received the diagnostic you sent, this seems related to a network issue. The app cannot connect to your fronius inverter. Could you please try executing a web request on your fronius inverter and paste the result please ? In a web browser on your network : http://192.168.178.37/solar_api/v1/GetInverterRealtimeData.cgi?Scope=System

Thanks

**Comment by DirkReimelt** [comment]
Don’t know if I did it right. When I press
The link above it shows:
{
   "Body" : {
      "Data" : {
         "DAY_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 0
            }
         },
         "PAC" : {
            "Unit" : "W",
            "Values" : {
               "1" : 0
            }
         },
         "TOTAL_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 17426930
            }
         },
         "YEAR_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 1626598
            }
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Inverter",
         "Scope" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2022-04-09T06:56:31+02:00"
   }
}

**Comment by DirkReimelt** [comment]
Just now I tried to add the inverter as device and it worked! That’s strange… but I understood it’s a network issue. So probably the App not showing data yesterday morning was a network issue too?

**Comment by DirkReimelt** [comment]
![Uploading 4E982F2B-E741-479C-92FA-30554A9D1DFC.jpeg…]()

**Comment by DirkReimelt** [comment]
![053FD692-1CEE-4544-A976-40F1134D68D5](https://user-images.githubusercontent.com/103278132/162557179-0e4204d3-cd19-43e0-9b48-b30d8e00a63c.jpeg)

**Comment by ThomasHoussin** [comment]
Seems ok, great. Just a thought : did you activate Nightmode on your Fronius inverter ? If not, it deactivates at night and the app won't get any data

**Comment by kurre435** [comment]
I had issues connecting  as well. Last fiemware update on gen24 inverter  disabled the API.
After enabling  the API it is working again.

Thanks for your exellent app.
