### ISSUE TITLE
Frequency on inverter page

### ISSUE THREAD

**Issue by gjefsjo** [ThomasHoussin/com.thomashoussin.fronius#27]
Can you make it show frequency on the inverter page/info?
And make so i can use: When frequency is above 51 Hz, turn on heater?

**Comment by ThomasHoussin** [comment]
I added the frequency on the inverter page, you can test it in the test version

**Comment by gjefsjo** [comment]
It works perfectly, thank you! Could you add a decimal?

**Comment by ThomasHoussin** [comment]
I made the change in the test version, frequency should now have a decimal
