### ISSUE TITLE
Inverter- no values in „Daily“, yearly“ and „total“

### ISSUE THREAD

**Issue by robgreiner** [ThomasHoussin/com.thomashoussin.fronius#3]
Hi
i use the App with Fronius GeEN24. 
There are no values in the Fields Daily“, "yearly“ and „total“
What is the Right Parameter For "Inverter Device-ID"?

**Comment by ThomasHoussin** [comment]
Hi, 
It should be autodetected. In the example from the API, it seems theses values are not reported for GEN24. 

Could you please open and paste the result here for : 
http://<your_ip>/solar_api/v1/GetInverterRealtimeData.cgi?Scope=System
 
Thanks

**Comment by robgreiner** [comment]
{
   "Body" : {
      "Data" : {
         "PAC" : {
            "Unit" : "W",
            "Value" : {
               "1" : 0.0
            }
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Inverter",
         "Scope" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2020-12-13T16:15:08+00:00"
   }
}

**Comment by ThomasHoussin** [comment]
It seems the data are not present. Could you please try :
http://<your_ip>/solar_api/v1/GetInverterRealtimeData.cgi?Scope=Device&DeviceId=1&DataCollection=CumulationInverterData

**Comment by robgreiner** [comment]
{
   "Body" : {
      "Data" : {
         "DeviceStatus" : {
            "InverterState" : "Sleeping"
         },
         "PAC" : {
            "Unit" : "W",
            "Value" : 0.0
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DataCollection" : "CumulationInverterData",
         "DeviceClass" : "Inverter",
         "DeviceId" : "1",
         "Scope" : "Device"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2020-12-13T16:36:22+00:00"
   }
}

**Comment by ThomasHoussin** [comment]
Sorry apparently the inverter doesn't report the data. May be you can try and paste the result for : http://<your_ip>/solar_api/v1/solar_api/v1/GetPowerFlowRealtimeData.fcgi

**Comment by robgreiner** [comment]
I think you mean: http://<your_ip>/solar_api/v1/GetPowerFlowRealtimeData.fcgi ;-)


{
   "Body" : {
      "Data" : {
         "Inverters" : {
            "1" : {
               "Battery_Mode" : "suspended",
               "DT" : 1,
               "P" : 0,
               "SOC" : 7.8000001907348633
            }
         },
         "Site" : {
            "BackupMode" : false,
            "BatteryStandby" : true,
            "E_Day" : null,
            "E_Total" : null,
            "E_Year" : null,
            "Meter_Location" : "grid",
            "Mode" : "bidirectional",
            "P_Akku" : 0.0,
            "P_Grid" : 501.44,
            "P_Load" : -501.44,
            "P_PV" : 0.0,
            "rel_Autonomy" : 0.0,
            "rel_SelfConsumption" : null
         },
         "Version" : "12"
      }
   },
   "Head" : {
      "RequestArguments" : {},
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2020-12-13T17:57:08+00:00"
   }
}

**Comment by robgreiner** [comment]
http://<your_ip>/solar_api/v1/GetMeterRealtimeData.cgi?Scope=Device&DeviceId=0

{
   "Body" : {
      "Data" : {
         "ACBRIDGE_CURRENT_ACTIVE_MEAN_01_F32" : 0.82999999999999996,
         "ACBRIDGE_CURRENT_ACTIVE_MEAN_02_F32" : 0.65400000000000003,
         "ACBRIDGE_CURRENT_ACTIVE_MEAN_03_F32" : 1.492,
         "ACBRIDGE_VOLTAGE_MEAN_12_F32" : 403.0,
         "ACBRIDGE_VOLTAGE_MEAN_23_F32" : 402.80000000000001,
         "ACBRIDGE_VOLTAGE_MEAN_31_F32" : 402.30000000000001,
         "COMPONENTS_MODE_ENABLE_U16" : 1.0,
         "COMPONENTS_MODE_VISIBLE_U16" : 1.0,
         "COMPONENTS_TIME_STAMP_U64" : 1607884770.0,
         "Details" : {
            "Manufacturer" : "Fronius",
            "Model" : "Smart Meter 63A",
            "Serial" : "20290366"
         },
         "GRID_FREQUENCY_MEAN_F32" : 50.0,
         "SMARTMETER_ENERGYACTIVE_ABSOLUT_MINUS_F64" : 276271.0,
         "SMARTMETER_ENERGYACTIVE_ABSOLUT_PLUS_F64" : 758556.0,
         "SMARTMETER_ENERGYACTIVE_CONSUMED_SUM_F64" : 758556.0,
         "SMARTMETER_ENERGYACTIVE_PRODUCED_SUM_F64" : 276271.0,
         "SMARTMETER_ENERGYREACTIVE_CONSUMED_SUM_F64" : 164340.0,
         "SMARTMETER_ENERGYREACTIVE_PRODUCED_SUM_F64" : 4118550.0,
         "SMARTMETER_FACTOR_POWER_01_F64" : -0.91000000000000003,
         "SMARTMETER_FACTOR_POWER_02_F64" : 0.87,
         "SMARTMETER_FACTOR_POWER_03_F64" : 0.89000000000000001,
         "SMARTMETER_FACTOR_POWER_SUM_F64" : 0.95999999999999996,
         "SMARTMETER_POWERACTIVE_01_F64" : 152.53999999999999,
         "SMARTMETER_POWERACTIVE_02_F64" : 123.19,
         "SMARTMETER_POWERACTIVE_03_F64" : 263.51999999999998,
         "SMARTMETER_POWERACTIVE_MEAN_01_F64" : 152.62530000000007,
         "SMARTMETER_POWERACTIVE_MEAN_02_F64" : 96.695733333333365,
         "SMARTMETER_POWERACTIVE_MEAN_03_F64" : 262.57773333333341,
         "SMARTMETER_POWERACTIVE_MEAN_SUM_F64" : 539.25,
         "SMARTMETER_POWERAPPARENT_01_F64" : 192.892,
         "SMARTMETER_POWERAPPARENT_02_F64" : 152.38200000000001,
         "SMARTMETER_POWERAPPARENT_03_F64" : 346.29320000000001,
         "SMARTMETER_POWERAPPARENT_MEAN_01_F64" : 193.81010433333333,
         "SMARTMETER_POWERAPPARENT_MEAN_02_F64" : 146.90871499999992,
         "SMARTMETER_POWERAPPARENT_MEAN_03_F64" : 345.7543329999998,
         "SMARTMETER_POWERAPPARENT_MEAN_SUM_F64" : 556.0,
         "SMARTMETER_POWERREACTIVE_01_F64" : 65.620000000000005,
         "SMARTMETER_POWERREACTIVE_02_F64" : -69.0,
         "SMARTMETER_POWERREACTIVE_03_F64" : -133.28999999999999,
         "SMARTMETER_POWERREACTIVE_MEAN_SUM_F64" : -136.66999999999999,
         "SMARTMETER_VALUE_LOCATION_U16" : 0.0,
         "SMARTMETER_VOLTAGE_01_F64" : 232.40000000000001,
         "SMARTMETER_VOLTAGE_02_F64" : 233.0,
         "SMARTMETER_VOLTAGE_03_F64" : 232.09999999999999,
         "SMARTMETER_VOLTAGE_MEAN_01_F64" : 231.51366666666672,
         "SMARTMETER_VOLTAGE_MEAN_02_F64" : 232.07900000000024,
         "SMARTMETER_VOLTAGE_MEAN_03_F64" : 231.26799999999997
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Meter",
         "DeviceId" : "0",
         "Scope" : "Device"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2020-12-13T18:39:31+00:00"
   }
}

**Comment by robgreiner** [comment]
/solar_api/GetAPIVersion.cgi

{
   "APIVersion" : 1,
   "BaseURL" : "/solar_api/v1/",
   "CompatibilityRange" : "1.5-17"
}

[42,0410,2012.pdf](https://github.com/ThomasHoussin/com.thomashoussin.fronius/files/5685344/42.0410.2012.pdf)

APi Documentation V 1.0

**Comment by ThomasHoussin** [comment]
Thanks. However, from what I can see, these values are not supported on your GEN24 : 

"E_Day" : null,
"E_Total" : null,
"E_Year" : null,

I'll have another look in the API, but i'm afraid nothing I can do...

**Comment by ThomasHoussin** [comment]
Sorry, but I don't think these values are reported in gen24.
