### ISSUE TITLE
Fronius Symo Gen24 hybrid inverter with BYD batteries not recognized

### ISSUE THREAD

**Issue by JohPePe** [ThomasHoussin/com.thomashoussin.fronius#31]
Hi!

I’ve got a solar farm consisting of two Symo 8 kW inverters, and as of today one Symo Gen24 hybrid with 33 kWh BYD batteries. And a smart meter, 3-phase, connected to the Gen24 inverter.
The app only recognizes the two Symo non hybrid inverters, nothing else.

I guess that’s because the app is talking to the datamanager at one of the non hybrid inverters.
A connection to solar.web would hopefully solve my problem.
What do you think, is it possible?

**Comment by ThomasHoussin** [comment]
Hi. I can have a look. If you have a smartmeter you should get some datas. 

Could you post the result of : 
- http://<your_ip>/solar_api/v1/GetInverterRealtimeData.cgi?Scope=System
- http://<your_ip>/solar_api/v1/GetStorageRealtimeData.cgi?Scope=System
- - http://<your_ip>/solar_api/v1/GetMeterRealtimeData.cgi.cgi?Scope=System

**Comment by JohPePe** [comment]
Hi Thomas!

I found the problem! 😀
Mr smartypants hadn’t enabled the api setting in the Gen24 😂
It’s working just fine now.
Thanks for your swift support!


/Johan
