### ISSUE TITLE
Inaccurate data GEN24 + TS65A

### ISSUE THREAD

**Issue by tutu81** [ThomasHoussin/com.thomashoussin.fronius#33]
I'm testing the APPS since some days and see differents issues as described here: https://community.homey.app/t/app-pro-support-for-fronius-inverters-and-smart-meters/38557/10?u=tutu81

1. GEN24: daily production isn’t updated at all (I installed the apps 8 days ago). Total production isn't accurate
2. Smart meter ts65A: Power from / to grid is not correctly set

How can I support you ? Do you need some additional infos / screenshoot ? 
I tested both 0.1.1 and 0.1.5 apps

Best,
Vince

**Comment by ThomasHoussin** [comment]
Hi
- For the production : it seems that the daily production is not reported in the API for GEN24. I already had a request (issue #3) and couldn't find the data. The value is available on solar.web, but not in the API as far as I know 
- For the smartmeter : the values are the total (not daily) energy injected or consumed, as reported by the smartmeter. The value in the Fronius app is the daily value. The daily values are available in the reporting app, but this is not supported by GEN24.
