### ISSUE TITLE
Unable to connect to homey

### ISSUE THREAD

**Issue by DV76** [ThomasHoussin/com.thomashoussin.fronius#34]
I have problems to connect my inverter. I get unable to connect when adding IP adress.

Can you please help me?

**Comment by ThomasHoussin** [comment]
Hi. 

Could you give me more informations so I can have a look ? do you use stable or test version for the app ? Which inverter ? Did you check that API connection is enabled in your firmware ? 

Could you laucnh in a web brower the URL and post the result please ? 

http://1<your_ip>/solar_api/v1/GetInverterRealtimeData.cgi?Scope=System

Thanks

**Comment by DV76** [comment]
No test version, installed it from this site https://homey.app/sv-se/app/com.thomashoussin.fronius/Fronius/

The inverter is Symo 15.0-3-M (1)

I tried the link with my IP but got the code 404 Not found

**Comment by DV76** [comment]
How/where do I see if the API connection is enabled?

**Comment by ThomasHoussin** [comment]
If the given url doesn't work, it's a network problem (not app problem). Are you able to connect on the administration web interface of Fronius ?

**Comment by DV76** [comment]
> If the given url doesn't work, it's a network problem (not app problem). Are you able to connect on the administration web interface of Fronius ?

Yes, if you mean at solarweb.com ?

**Comment by DV76** [comment]
Think it was the wrong IP, I got this now will using your link

{
   "Body" : {
      "Data" : {
         "DAY_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 69970
            }
         },
         "PAC" : {
            "Unit" : "W",
            "Values" : {
               "1" : 8220
            }
         },
         "TOTAL_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 9420210
            }
         },
         "YEAR_ENERGY" : {
            "Unit" : "Wh",
            "Values" : {
               "1" : 9420213
            }
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Inverter",
         "Scope" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2022-07-10T17:03:54+02:00"
   }
}

**Comment by DV76** [comment]
And now it worked to add the app, thx for the support! 🙏🏻

**Comment by ThomasHoussin** [comment]
No problem, thanks.

**Comment by ThomasHoussin** [comment]
You have a specific parameter (in fronius web interface) in the settings section IIRC ; something like night mode, it activates reporting and API during the night.

**Comment by DV76** [comment]
Do you have a picture where I change it so maybe I can find it? 🙏🏻

**Comment by DV76** [comment]
Did you have any screenshot to help me out?😎

**Comment by ThomasHoussin** [comment]
Have a look at this parameter : 
![image](https://user-images.githubusercontent.com/6912005/180884904-5398142d-2840-415b-a31e-4cc554a219c3.png)

**Comment by StarkRobin** [comment]
I had the exact same issue with not being able to connect from the Homey app even though the ip-address was correct. I tried multiple times and even gave the inverter a static ip-address in my router but it didn't work. I then found this closed issue and tried opening the link http://<your_ip>/solar_api/v1/GetInverterRealtimeData.cgi?Scope=System

I then tried to connect once more in the Homey app - and like magic - it now worked.

Was it just a coincidence or do we first need to access that url? Maybe you could add that request to the pairing process or at least add the information in the App Description in Homey?
