### ISSUE TITLE
Homey-App for Fronius 

### ISSUE THREAD

**Issue by arni64** [ThomasHoussin/com.thomashoussin.fronius#35]
Hello Thomas Houssin,
It which format is the IP Adress? If I add   192.168.178.88   it shows UNABLE TO CONNECT.
It which format is the HOSTNAME? If I add   PVAnlage1   it shows UNABLE TO CONNECT.
If I add         PVAnlage1/192.168.178.88       it shows UNABLE TO CONNECT. 

What’s wrong?

I'm trying v0.1.1 and experimental v0.1.5 both with the same error.

Thanks for help.

**Comment by ThomasHoussin** [comment]
Could you please have a look at #34 and post the result of the web request please ? Thanks

**Comment by arni64** [comment]
Hi.

I'am using the experimentell version v0.1.5.
I'am using a Symo GEN24 8.0 Plus inverter.

I checked the setting "API connection". It was disabled.

and well it works fine.

Many thanks for the help

thanks
