### ISSUE TITLE
Daily Production issue

### ISSUE THREAD

**Issue by surdr** [ThomasHoussin/com.thomashoussin.fronius#40]
Hi,
I use version 0.11 from your homey app with a fronius gen24 10kw inverter. Power, voltage and total production are working well. But the daily and yearly production is always zero? Is this a bug?

**Comment by ThomasHoussin** [comment]
Hi. I had a look, this is the "correct" value : the API description states for day and year energy : 'GEN24: will always report null'. Total production should work as expected.
