### ISSUE TITLE
Energy From / To grid

### ISSUE THREAD

**Issue by PeetersJan** [ThomasHoussin/com.thomashoussin.fronius#43]
Hi,
In the Fronius webinterface, there is a nice graph showing the daily "Energy from Grid", "Energy consumed directly" and "Energy to grid". It would be really interesting to get this information inside your app as well.

Do  you think this might be feasable?

![image](https://user-images.githubusercontent.com/39444710/224687605-eb6c9e93-4958-4595-84f4-9c8890024c28.png)

![image](https://user-images.githubusercontent.com/39444710/224687865-254ff364-2c07-4461-a199-0de1a3ad75bb.png)

Thank you!

**Comment by ThomasHoussin** [comment]
Did you try the reporting app (you can add it as if you were adding a fronius device) ? You have these information in this app, if it's supported by your inverter.

**Comment by ThomasHoussin** [comment]
![image](https://user-images.githubusercontent.com/6912005/224692362-ebad3c43-658e-40b1-93fd-a504d63d8b56.png)

**Comment by PeetersJan** [comment]
> Did you try the reporting app (you can add it as if you were adding a fronius device) ? You have these information in this app, if it's supported by your inverter.

Hi,
It doesn't seem to work.
As a "site name" / "device name" , I entered "Fronius" and uner 'IP/hostname', the IP of my Fronius inverter.
I get an 'unknown error' as result.
I have tested this on both versions 0.1.1 and 0.1.7 experimental.

My inverter is a Primo GEN24 5.0 Plus

Any ideas?

**Comment by ThomasHoussin** [comment]
Hi. I had a look and the API I use in PowerFlow (GetPowerFlowRealtimeData) and in Reporting (GetArchiveData) are not supported on GEN24. I didn't find another way to get these values for now.
