### ISSUE TITLE
Smartmeter

### ISSUE THREAD

**Issue by holgerschuetz** [ThomasHoussin/com.thomashoussin.fronius#46]
Hi Thomas,
I have a fronius Symo Gen24 and a Fronius SmartMeter. The SmartMeter is directly wired into the inverter. How do I get the SmartMeter data from your Fronius App. I have the Homey 2019 and the Homey Pro 2023.

When I try to add the smart meter it ask me for the IP/Hostname. I have only the ip of the inverter as the smart meter is connected directly to the inverter.

Thanks for your support.

Cheers
Holger

**Comment by ThomasHoussin** [comment]
You should add the IP of the inverter, and if the smart meter is configured on it it will work

**Comment by ThomasHoussin** [comment]
On gen24 you have to activate API access on the inverter ; there's a specific parameter on the inverter to allow access

**Comment by Effendi68** [comment]
API Access is active. I can connect to the inverter without problems but I couldn‘t connect to the Fronius PowerMeter.

**Comment by aahh86** [comment]
I also have problem with connecting to Smartmeter.

Fronius Hybrid 2019.
Smartmeter is visible at local adress.

Inverter is connected to Homey app.
BYD batteri is connected, also works in the Homey app.
When trying to add smartmeter "Unable to connect".

As I read above there shouln't be any API-issues with this inverter? Any solutions?

**Comment by ThomasHoussin** [comment]
Could you please post the result of the request : http://<your_ip>/solar_api/v1/GetMeterRealtimeData.cgi?Scope=System

**Comment by aahh86** [comment]
{
   "Body" : {
      "Data" : {
         "0" : {
            "Current_AC_Phase_1" : 3.052,
            "Current_AC_Phase_2" : 6.4669999999999996,
            "Current_AC_Phase_3" : 3.2930000000000001,
            "Details" : {
               "Manufacturer" : "Fronius",
               "Model" : "Smart Meter 63A",
               "Serial" : "18490257"
            },
            "Enable" : 1,
            "EnergyReactive_VArAC_Sum_Consumed" : 28825650,
            "EnergyReactive_VArAC_Sum_Produced" : 32841940,
            "EnergyReal_WAC_Minus_Absolute" : 7289981,
            "EnergyReal_WAC_Plus_Absolute" : 18330529,
            "EnergyReal_WAC_Sum_Consumed" : 18330529,
            "EnergyReal_WAC_Sum_Produced" : 7289981,
            "Frequency_Phase_Average" : 49.899999999999999,
            "Meter_Location_Current" : 0,
            "PowerApparent_S_Phase_1" : 721.49279999999999,
            "PowerApparent_S_Phase_2" : 1504.8708999999999,
            "PowerApparent_S_Phase_3" : 776.48940000000005,
            "PowerApparent_S_Sum" : 169.61000000000001,
            "PowerFactor_Phase_1" : 0.98999999999999999,
            "PowerFactor_Phase_2" : -0.98999999999999999,
            "PowerFactor_Phase_3" : -0.98999999999999999,
            "PowerFactor_Sum" : 0,
            "PowerReactive_Q_Phase_1" : 62.390000000000001,
            "PowerReactive_Q_Phase_2" : 196.41,
            "PowerReactive_Q_Phase_3" : -89.189999999999998,
            "PowerReactive_Q_Sum" : 169.61000000000001,
            "PowerReal_P_Phase_1" : -706.33000000000004,
            "PowerReal_P_Phase_2" : 1467.1800000000001,
            "PowerReal_P_Phase_3" : -759.30999999999995,
            "PowerReal_P_Sum" : 1.54,
            "TimeStamp" : 1686299882,
            "Visible" : 1,
            "Voltage_AC_PhaseToPhase_12" : 406.30000000000001,
            "Voltage_AC_PhaseToPhase_23" : 405.69999999999999,
            "Voltage_AC_PhaseToPhase_31" : 408.89999999999998,
            "Voltage_AC_Phase_1" : 236.40000000000001,
            "Voltage_AC_Phase_2" : 232.69999999999999,
            "Voltage_AC_Phase_3" : 235.80000000000001
         }
      }
   },
   "Head" : {
      "RequestArguments" : {
         "DeviceClass" : "Meter",
         "Scope" : "System"
      },
      "Status" : {
         "Code" : 0,
         "Reason" : "",
         "UserMessage" : ""
      },
      "Timestamp" : "2023-06-09T10:38:03+02:00"
   }
}

**Comment by ThomasHoussin** [comment]
OK I think I fixed this bug in the version version ; could you please try the test version here ? https://homey.app/fr-fr/app/com.thomashoussin.fronius/Fronius/test/

**Comment by aahh86** [comment]
Works fine now! This is one of the big reasons why I bought Homey. Donate will come in a couple of days!

**Comment by Effendi68** [comment]
> OK I think I fixed this bug in the test version ; could you please try the test version here ? https://homey.app/fr-fr/app/com.thomashoussin.fronius/Fronius/test/

Thank you, with the test version it works.

**Comment by tomac74** [comment]
Hello,
i have a problem with the app. My Inverter is a Gen24...
The Daily Production and the Yearly Production are not shown in the App.
I have 2023 Homey Pro.

Thanks very much
Thomas

**Comment by ThomasHoussin** [comment]
Hi. 

These are not available on Gen24 with Fronius API, that's why there aren't reported

Thomas
