### ISSUE TITLE
Hostname

### ISSUE THREAD

**Issue by LeeJenFro** [ThomasHoussin/com.thomashoussin.fronius#54]
Typing the ip address doesn’t work for me. Any clues on what this should be? Many thanks.

**Comment by ThomasHoussin** [comment]
Did you check that API access is activated in your inverter ? You can try this by executing the request http://<your_ip>/solar_api/v1/GetInverterRealtimeData.cgi?Scope=System

According to Fronius guide : 

![image](https://github.com/ThomasHoussin/com.thomashoussin.fronius/assets/6912005/f28f1966-2eb9-4589-bb32-5f0abd7b999b)
