### ISSUE TITLE
Information from smartmeter

### ISSUE THREAD

**Issue by sssvinggg** [ThomasHoussin/com.thomashoussin.fronius#55]
Hi.
I have a inverter gen24 storage and smartmeter. I can't get information from my smartmeter. Ec "current has change" in advanced flow.
Can someone help me?
Take care 👍

**Comment by ThomasHoussin** [comment]
It is supported ; you have to install the Fronius app, create the smartemeter device. After that, when creating a flow (standard or advanced), you can add a When card. The smartmeter device offers several triggers (based on current, energy, frequency,...)
