### ISSUE TITLE
No data in Reporting

### ISSUE THREAD

**Issue by effin** [ThomasHoussin/com.thomashoussin.fronius#62]
I have a Fronius, Smart meter IP connected with cable and a Homey Pro. Adding Fronius app device "Reporting" but it just shows "-". No error messages.

![Screenshot_20241027_140457_Homey](https://github.com/user-attachments/assets/17ab2fed-2c86-4b37-9545-10bbe65999a0)

**Comment by ThomasHoussin** [comment]
Hi. Did you try the app smartmeter app, and does it work ? Do you have a GEN 24 or Tauro inverter ? If that's the case GEN24/Tauro does not provide access to history data, so it won't work

**Comment by effin** [comment]
Not sure what the smartmeter app is? I tried to add a device as the Fronius app "Smartmeter" giving the IP of my inverterter, but it says "Unable to connect". My inverter is a GEN24. The Solar.web app works fine.
![Screenshot_20241025_135404_Solarweb](https://github.com/user-attachments/assets/ac0df745-fca6-4387-be9a-9fe5f08cf4a2)

**Comment by ThomasHoussin** [comment]
Did you activate the access in Fronius web ? You have to connect on your fronius webUI (not solarweb) and activate the access. 

According to the documentation for GEN24 : 
![image](https://github.com/user-attachments/assets/e59cac61-80f0-45e9-9457-0d3c6d71a4be)

**Comment by effin** [comment]
Ah! No it was not enabled. So I toggled it. But at the same time it lost wifi so now I can't see it at all. Going into Communication/Network (where the wifi is set up) page is just spinning :(

**Comment by effin** [comment]
It works!! Had to reboot the inverter since the UI was unresponsive. 
Thanks so much for your help :)
