### ISSUE TITLE
To connect Fronius inverter to Fronius app in Homey Pro (2023)

### ISSUE THREAD

**Issue by erikroland** [ThomasHoussin/com.thomashoussin.fronius#63]
Trying to get connection as described without results.

A Fronius inverter Symo Gen24 8.0 Plus. Instructions are
![20241027_140426 - kopia](https://github.com/user-attachments/assets/271664fa-2500-4f6b-afed-ab2175504072)
 enclosed.

IP 169.254.0.180 are not accepted by Fronius app in Homey Pro.

Suggestions how to proceed for success?

**Comment by ThomasHoussin** [comment]
Hi, Are-you sure this IP address is reachable from you local network ? I guess you have to enter this address on a web browser connected on the fronius, then set up (using dhcp probably) and then connect fronius on your local network. However this is not related to the app, rather to your network.

**Comment by erikroland** [comment]
Tnks for Quick respond. I will investigate and come back w feedback whatever the results will be /Roland Skickat från min Galaxy
-------- Originalmeddelande --------Från: Thomas Houssin ***@***.***> Datum: 2024-10-27  16:34  (GMT+01:00) Till: "ThomasHoussin/com.thomashoussin.fronius" ***@***.***> Kopia: erikroland ***@***.***>, Author ***@***.***> Ämne: Re: [ThomasHoussin/com.thomashoussin.fronius] To connect Fronius inverter to Fronius app in Homey Pro (2023) (Issue #63) 
Hi, Are-you sure this IP address is reachable from you local network ? I guess you have to enter this address on a web browser connected on the fronius, then set up (using dhcp probably) and then connect fronius on your local network. However this is not related to the app, rather to your network.
